CREATE TABLE game (gamenum INTEGER PRIMARY KEY AUTOINCREMENT, title VARCHAR(128), platform VARCHAR(16));
CREATE TABLE faq (faqnum INTEGER PRIMARY KEY AUTOINCREMENT, gamenum INTEGER, title VARCHAR(128), author VARCHAR(128), date VARCHAR(8), version VARCHAR(16));
