#!/usr/bin/python

import curses
import sys
import urllib
import subprocess
import scrape

def clear(stdscr):
	stdscr.clear()
	stdscr.border(0)

def get_input(stdscr, y, x, prompt, strlen):
	stdscr.addstr(y, x, prompt)
	stdscr.refresh()
	curses.echo()
	user_input = stdscr.getstr(y, x + len(prompt), strlen)
	curses.noecho()
	return user_input

def search(stdscr):
	clear(stdscr)
	search = get_input(stdscr, 1, 1, 'Enter game search: ', 60)
	choose_search_result(stdscr, scrape.game_search(search))

def choose_search_result(stdscr, results):
	'''Displays a menu for the user to choose a game from a list of search results.
	'''
	choice = 0
	y = 2
	x = 1
	while True:
		clear(stdscr)
		stdscr.addstr(1, 1, 'Search Results:')
		# Display all search results
		for i, result in enumerate(results):
			if i == choice:
				flag = curses.A_REVERSE
			else:
				flag = 0
			stdscr.addstr(i + y, x, '%s - %s' % result[:2], flag)
		stdscr.refresh()
		c = stdscr.getch()
		
		# Quit on q
		if c == ord('q'):
			sys.exit(0)
		# Scroll up/down list
		elif c == curses.KEY_DOWN:
			choice += 1
			choice = choice % len(results)
		elif c == curses.KEY_UP:
			choice -= 1
			choice = choice % len(results)
		# Break out of loop on enter key which will bring the user to the FAQ screen
		elif c == ord('\n'):
			break
	
	# Move to the FAQs display screen
	choose_faq(stdscr, results[choice][2])

def choose_faq(stdscr, faq_url):
	'''Displays a menu to choose a FAQ for a game
	Assumes that faq_url is a url to the correct page
	'''
	clear(stdscr)
	stdscr.addstr(1, 1, 'FAQs')
	# Scrape the FAQs page
	faqs = scrape.faqs(faq_url)
	choice = 0
	y = 2
	x = 1
	# Show the FAQs in a menu
	while True:
		# Display all search results
		for i, faq in enumerate(faqs):
			if i == choice:
				flag = curses.A_REVERSE
			else:
				flag = 0
			stdscr.addstr(i + y, x, '%s - %s - %s - %s - %s' % faq[:5], flag)
		stdscr.refresh()
		c = stdscr.getch()

		# Quit on q
		if c == ord('q'):
			sys.exit(0)
		# Scroll up/down list
		elif c == curses.KEY_DOWN:
			choice += 1
			choice = choice % len(faqs)
		elif c == curses.KEY_UP:
			choice -= 1
			choice = choice % len(faqs)
		# Break out of loop on enter key which will bring the user to the FAQ screen
		elif c == ord('\n'):
			break
	
	# Since the faq document is in html we need to scrape the page to get the plain text download url
	text_faq = scrape.plaintext_faq(faqs[choice][5])
	read_faq(text_faq)

def read_faq(doc_url):
	'''Opens doc_url, downloads the FAQ, and opens it in the system default editor
	'''
	urllib.urlretrieve(doc_url, '/tmp/faq.txt')
	subprocess.call(['vim', '/tmp/faq.txt'])

if __name__ == '__main__':
	while True:
		# Initializes curses nicely, undoing all changes if the program crashes
		curses.wrapper(search)
